version: "2.1"
orbs:
  aws-ecr: circleci/aws-ecr@6.15
  aws-ecs: circleci/aws-ecs@2.0.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          repo: "hello-fargate"
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          cluster-name: "${MY_APP_PREFIX}-cluster"
          container-image-name-updates: "container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}"
          family: "${MY_APP_PREFIX}-service"
          requires:
            - aws-ecr/build-and-push-image
family: "Monorevo-Test" # ECSのタスク定義名
cluster-name: "Monorevo-Cluster" # ECSクラスター名
service-name: "Monorevo-service" # ECSのサービス名
container-image-name-updates: "container=${ECS_PARAM_FAMILY},tag=${CIRCLE_SHA1}" # タスク定義で指定しているコンテナ名
