# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
        filters:
          branches:
            only:
              - rc
# version: "2.1"
# orbs:
#   aws-ecr: circleci/aws-ecr@6.15
#   aws-ecs: circleci/aws-ecs@2.0.0
# workflows:
#   build-and-deploy:
#     jobs:
#       - aws-ecr/build-and-push-image:
#           account-url: AWS_ECR_ACCOUNT_URL
#           region: AWS_DEFAULT_REGION
#           repo: "hello-fargate"
#           tag: "${CIRCLE_SHA1}"
#       - aws-ecs/deploy-service-update:
#           cluster-name: "Monorevo-Cluster"
#           family: "Monorevo-Test"
#           service-name: "Monorevo-service"
#           container-image-name-updates: "container=hello-fargate,tag=${CIRCLE_SHA1}" # タスク定義で指定しているコンテナ名
#           requires:
#             - aws-ecr/build-and-push-image
# # family: "Monorevo-Test" # ECSのタスク定義名
# # cluster-name: "Monorevo-Cluster" # ECSクラスター名
# # service-name: "Monorevo-service" # ECSのサービス名
# # container-image-name-updates: "container=hello-fargate,tag=${CIRCLE_SHA1}" # タスク定義で指定しているコンテナ名
