version: "2.1"
orbs:
  aws-ecr: circleci/aws-ecr@6.15
  aws-ecs: circleci/aws-ecs@2.0.0
  aws-cli: circleci/aws-cli@2.0.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
          repo: "hello-fargate"
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          cluster-name: "Monorevo-Cluster"
          family: "Monorevo-Test"
          service-name: "Monorevo-service"
          container-image-name-updates: "container=hello-fargate,tag=${CIRCLE_SHA1}"
